# Generated by Django 4.0.4 on 2022-06-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
