# Generated by Django 4.0.4 on 2022-06-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursal_image', models.ImageField(default='', upload_to='shop/coursal_images')),
            ],
        ),
    ]
