# Generated by Django 4.0.4 on 2022-06-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_coursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_initial_price',
            field=models.IntegerField(default='75852'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_rating',
            field=models.IntegerField(default=44),
        ),
    ]
