# Generated by Django 4.0.4 on 2022-06-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_product_initial_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_initial_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_rating',
        ),
    ]
