# Generated by Django 4.0.4 on 2022-06-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
