# Generated by Django 4.0.4 on 2022-06-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_contact_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='v', max_length=100),
            preserve_default=False,
        ),
    ]
