# Generated by Django 4.0.4 on 2022-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_id_product_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursal',
            name='id',
        ),
        migrations.AddField(
            model_name='coursal',
            name='coursal_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
