# Generated by Django 4.0.4 on 2022-07-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_comment_image_reviewimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Review',
        ),
    ]
