# Generated by Django 4.0.4 on 2022-07-30 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_review_dislikes_review_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewimage',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commentimage', to='shop.review'),
        ),
    ]
