# Generated by Django 4.0.4 on 2022-07-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_rename_images_reviewimage_image_remove_review_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(default='', upload_to='shop/Reviewimages/'),
        ),
    ]
