# Generated by Django 4.0.4 on 2022-07-31 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_reviewimage_image_alter_reviewimage_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimage',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
            preserve_default=False,
        ),
    ]
