# Generated by Django 4.0.4 on 2022-07-31 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_cateogory_alter_product_product_desc_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cateogory',
            new_name='Category',
        ),
    ]
