# Generated by Django 4.0.4 on 2022-07-31 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_productdescriptionimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='SubCategory',
            new_name='Category',
        ),
    ]
