# Generated by Django 4.0.4 on 2022-08-01 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Sub_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.subcategory'),
        ),
    ]
