# Generated by Django 4.0.4 on 2022-08-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
