# Generated by Django 4.0.4 on 2022-08-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_rename_staticimages_staticimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticimage',
            name='cat',
            field=models.CharField(default='', max_length=500),
        ),
    ]
