# Generated by Django 4.0.4 on 2022-08-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalprice',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
