# Generated by Django 4.0.4 on 2022-08-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_alter_product_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.TextField(max_length=10000),
        ),
    ]
