# Generated by Django 4.0.4 on 2022-08-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='heading',
            field=models.CharField(max_length=1000),
        ),
    ]
