# Generated by Django 4.0.4 on 2022-08-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursal',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
