# Generated by Django 4.0.4 on 2022-08-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_coursal_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursal',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
