# Generated by Django 4.0.4 on 2022-08-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_alter_coursal_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='what_is_in_the_box',
            field=models.TextField(default='kjh'),
            preserve_default=False,
        ),
    ]
