# Generated by Django 4.0.4 on 2022-09-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_product_what_is_in_the_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='shop/Category_thumbnail'),
        ),
    ]
