# Generated by Django 4.0.4 on 2022-12-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_alter_productdescriptionimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_shipping_charges',
            field=models.IntegerField(default=0),
        ),
    ]
