# Generated by Django 4.0.4 on 2023-02-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_product_product_techinical_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='static/Category_thumbnail'),
        ),
        migrations.AlterField(
            model_name='coursal',
            name='coursal_image',
            field=models.ImageField(default='', upload_to='static/coursal_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='static/thumbnail_image'),
        ),
        migrations.AlterField(
            model_name='productdescriptionimages',
            name='image',
            field=models.ImageField(default='static/placeholder.png', upload_to='static/DescImages'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to='static/Reviewimages'),
        ),
        migrations.AlterField(
            model_name='staticimage',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
