# Generated by Django 4.0.4 on 2023-02-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0072_alter_category_image_alter_coursal_coursal_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='shop/Category_thumbnail'),
        ),
        migrations.AlterField(
            model_name='coursal',
            name='coursal_image',
            field=models.ImageField(default='', upload_to='shop/coursal_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='shop/thumbnail_image'),
        ),
        migrations.AlterField(
            model_name='productdescriptionimages',
            name='image',
            field=models.ImageField(default='shop/placeholder.png', upload_to='shop/DescImages'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to='shop/Reviewimages'),
        ),
        migrations.AlterField(
            model_name='staticimage',
            name='image',
            field=models.ImageField(upload_to='shop/static'),
        ),
    ]
