# Generated by Django 4.1.7 on 2023-02-24 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0076_alter_category_image_alter_coursal_coursal_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReviewImage",
        ),
    ]
