# Generated by Django 4.1.7 on 2023-03-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0078_reviewimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewimage",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_images",
                to="shop.review",
            ),
        ),
    ]
