# Generated by Django 4.1.7 on 2023-03-14 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0080_alter_productdescriptionimages_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdescriptionimages",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_description_images",
                to="shop.product",
            ),
        ),
    ]
