# Generated by Django 4.1.7 on 2023-03-14 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0081_alter_productdescriptionimages_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewimage",
            name="product",
        ),
    ]
