# Generated by Django 4.1.7 on 2023-04-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0084_alter_dislike_content_object_alter_dislike_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Like",
                to="shop.review",
            ),
        ),
    ]
