# Generated by Django 4.1.7 on 2023-04-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0085_alter_like_content_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="specifications",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="category",
            name="specifications_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_techinical_details",
            field=models.TextField(blank=True, default=" ", null=True),
        ),
    ]
