# Generated by Django 4.1.7 on 2023-04-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0086_category_specifications_category_specifications_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_specifications",
            field=models.JSONField(blank=True, default="{}"),
        ),
    ]
