# Generated by Django 4.1.7 on 2023-04-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0087_product_product_specifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_specifications",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
