# Generated by Django 4.1.7 on 2023-04-13 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0088_alter_product_product_specifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_techinical_details",
        ),
    ]
