# Generated by Django 4.0.4 on 2022-08-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='product',
        ),
    ]
