# Generated by Django 4.0.4 on 2022-08-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_alter_order_product_alter_order_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_type',
            new_name='work_address',
        ),
    ]
