# Generated by Django 4.0.4 on 2022-08-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
