# Generated by Django 4.0.4 on 2022-09-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0012_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
    ]
