# Generated by Django 4.0.4 on 2022-12-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0014_order_address_alter_order_shipped_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(),
        ),
    ]
