# Generated by Django 4.0.4 on 2022-12-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0015_alter_order_shipped_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='outfordelivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(null=True),
        ),
    ]
