# Generated by Django 4.1.7 on 2023-02-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0018_alter_address_user_alter_order_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="order",
            name="signature",
            field=models.CharField(default="", max_length=150),
        ),
    ]
