# Generated by Django 4.1.7 on 2023-02-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0020_alter_order_order_id_alter_order_payment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_id",
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name="order",
            name="signature",
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
