# Generated by Django 4.1.7 on 2023-02-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0022_order_canceled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivered_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="outfordelivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipped_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
