# Generated by Django 4.1.7 on 2023-02-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserProfile", "0024_alter_order_final_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="final_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_id",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="order",
            name="signature",
            field=models.CharField(max_length=150),
        ),
    ]
